---
- name: Enable Red Hat Repository
  yum_repository:
    name: rhel-7-server-extras-rpms
    enable: yes
  when:
      - ansible_distribution == "RedHat"

- name: Install Kubernetes Packages
  yum: name={{ item }} state=present
  with_items:
    - docker
    - kubernetes
    - etcd
    - flannel
    
- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable firewalld
  systemd: name=firewalld enabled=no state=stopped

- name: Copy kubernetes config file
  copy: src=config dest=/etc/kubernetes/config

- name: Copy /etc/sysconfig/flanneld
  copy: src=flanneld dest=/etc/sysconfig/flanneld
